### ISSUE TITLE
Custom merging of props and context

### ISSUE THREAD

**Issue by peterszerzo** [Contiamo/react-connect-context#1]
# Issue Summary

Currently, context and props are shallow-merged when using the higher-order component exposed in this library. Sometimes a custom merge method might be preferable, like `{ context, ...props }` as opposed to `{ ...context, ...props }` in order to avoid field collisions, or to work with a fully separate context interface more easily in a typed environment.

## Proposed Solution:

Export a separate `customConnectContext` that takes a `(props, context) => newProps` method that specifies the way merging should be done, and returns a method with the same API as the one that's currently exported in the library.

This way, this default connect function could be expressed like so:

`connectContext = customConnectContext((props, context) => { ...context, ...props })`

**Comment by TejasQ** [comment]
I like this! We could have this `mergeMethod` function as a second parameter to the function, thereby changing the API as so:

```jsx
connectContext(ContextConsumer, (props, context) => ({ ...context, ...props }))(MyComponent)
```

This would then become a default parameter that shallow merges, which can be overridden as needed, thereby not being a _breaking change_ to the API.

What do you think?

**Comment by peterszerzo** [comment]
That's a great idea - way better than another higher-order function on top!

**Comment by aulisius** [comment]
Isn't this the same as `connect`'s mergeProps ?

**Comment by TejasQ** [comment]
@aulisius, yup. Would you like to implement this feature?
